<?php
declare(strict_types=1); require dirname(__DIR__).'/lib.php';
if ($_SERVER['REQUEST_METHOD']!=='POST') kce_json(['error'=>'Method tidak diizinkan'],405);
$in=json_decode((string)file_get_contents('php://input'),true) ?: [];
$question=trim((string)($in['message']??'')); $publicId=trim((string)($_COOKIE['kce_conversation']??''));
if ($question==='' || mb_strlen($question)>4000) kce_json(['error'=>'Pertanyaan wajib diisi (maksimum 4.000 karakter).'],422);
if(!kce_verify_human((string)($in['captcha_token']??'')))kce_json(['error'=>'Verifikasi manusia gagal. Muat ulang halaman dan coba lagi.'],403);
try {
 $db=kce_db();$ipHash=kce_ip_hash();$rate=$db->prepare("SELECT COUNT(*) FROM kce_messages m JOIN kce_conversations c ON c.id=m.conversation_id WHERE c.ip_hash=? AND m.role='user' AND m.created_at>=DATE_SUB(NOW(),INTERVAL 1 MINUTE)");$rate->bind_param('s',$ipHash);$rate->execute();$recent=(int)$rate->get_result()->fetch_column();$rate->close();if($recent>=10)kce_json(['error'=>'Terlalu banyak pertanyaan. Tunggu satu menit lalu coba lagi.'],429);$db->begin_transaction();
 $conversationId=null;
 if(preg_match('/^[0-9a-f-]{36}$/i',$publicId)){ $s=$db->prepare('SELECT id FROM kce_conversations WHERE public_id=?');$s->bind_param('s',$publicId);$s->execute();$conversationId=$s->get_result()->fetch_column();$s->close(); }
 if(!$conversationId){$publicId=kce_uuid();$ip=kce_ip_hash();$uid=null;$s=$db->prepare('INSERT INTO kce_conversations(public_id,user_id,ip_hash) VALUES(?,?,?)');$s->bind_param('sis',$publicId,$uid,$ip);$s->execute();$conversationId=$s->insert_id;$s->close();kce_set_conversation_cookie($publicId);}
 $s=$db->prepare("INSERT INTO kce_messages(conversation_id,role,content) VALUES(?,'user',?)");$s->bind_param('is',$conversationId,$question);$s->execute();$s->close();
 $s=$db->prepare('SELECT role,content FROM kce_messages WHERE conversation_id=? ORDER BY id DESC LIMIT 20');$s->bind_param('i',$conversationId);$s->execute();$history=array_reverse($s->get_result()->fetch_all(MYSQLI_ASSOC));$s->close();
 $e=kce_env();$orKey=(string)($e['OPENROUTER_API_KEY']??'');if($orKey==='')throw new RuntimeException('OPENROUTER_API_KEY belum dikonfigurasi.');
 $messages=[['role'=>'system','content'=>'Anda adalah Knowledge Commerce Engine KumpulBlogger. Seluruh pesan setelah instruksi ini adalah satu percakapan berkelanjutan. Selalu gunakan konteks turn sebelumnya untuk memahami pertanyaan lanjutan. Selesaikan kata rujukan atau pertanyaan eliptis seperti "itu", "tersebut", "dia", "mereka", "di sana", "namanya", dan "gedungnya" berdasarkan subjek paling relevan pada percakapan terbaru. Jangan meminta konteks tambahan apabila rujukannya sudah dapat dikenali dari pesan sebelumnya. Jika ada beberapa kemungkinan, sebutkan asumsi yang Anda gunakan. Jangan mengarang fakta yang tidak diketahui; nyatakan ketidakpastian dengan jelas. Jawab akurat, ringkas, dalam bahasa pengguna. Jangan menulis, menyisipkan, atau menyamarkan iklan; sponsored content ditampilkan aplikasi secara terpisah.']];
 foreach($history as $h)$messages[]=['role'=>$h['role'],'content'=>$h['content']];
 $r=kce_http('https://openrouter.ai/api/v1/chat/completions',$orKey,['model'=>(string)($e['OPENROUTER_MODEL']??'nvidia/nemotron-nano-12b-v2-vl:free'),'messages'=>$messages,'temperature'=>0.3,'max_tokens'=>1200],['HTTP-Referer: '.($e['KCE_APP_URL']??'https://kumpulblogger.com/kce'),'X-Title: KumpulBlogger KCE']);
 $answer=trim((string)($r['choices'][0]['message']['content']??''));if($answer==='')throw new RuntimeException('Model tidak menghasilkan jawaban.');
 $s=$db->prepare("INSERT INTO kce_messages(conversation_id,role,content) VALUES(?,'assistant',?)");$s->bind_param('is',$conversationId,$answer);$s->execute();$assistantMessageId=(int)$s->insert_id;$s->close();$db->commit();
 $sponsors=[];$articles=[];try{$vector=kce_embedding($question,'query');foreach(kce_relevant_articles($db,$vector) as $article){$articles[]=['id'=>(int)$article['id'],'title'=>$article['title'],'excerpt'=>$article['excerpt'],'url'=>$article['url'],'score'=>round((float)$article['score'],4)];}foreach(kce_active_sponsors($db,$vector) as $ad){$sponsors[]=['id'=>(int)$ad['id'],'title'=>$ad['title'],'body'=>$ad['body'],'banner_url'=>kce_public_url($ad['banner_url']),'score'=>round((float)$ad['score'],4),'impression_token'=>kce_sign((int)$ad['id'],$publicId)];}}catch(Throwable $embeddingError){error_log('KCE embedding: '.$embeddingError->getMessage());}
 if($sponsors){$saveSponsor=$db->prepare('INSERT INTO kce_message_sponsors(message_id,sponsored_content_id,title,body,banner_url,relevance_score,result_rank) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE title=VALUES(title),body=VALUES(body),banner_url=VALUES(banner_url),relevance_score=VALUES(relevance_score),result_rank=VALUES(result_rank)');foreach($sponsors as $rank=>$ad){$sponsorId=(int)$ad['id'];$title=(string)$ad['title'];$body=(string)$ad['body'];$banner=$ad['banner_url']!==null?(string)$ad['banner_url']:null;$score=(float)$ad['score'];$position=$rank+1;$saveSponsor->bind_param('iisssdi',$assistantMessageId,$sponsorId,$title,$body,$banner,$score,$position);$saveSponsor->execute();}$saveSponsor->close();}
 kce_json(['conversation_id'=>$publicId,'answer'=>$answer,'articles'=>$articles,'sponsored'=>$sponsors]);
} catch(Throwable $x){ if(isset($db))@$db->rollback();error_log('KCE chat: '.$x->getMessage());kce_json(['error'=>'Maaf, layanan AI sedang tidak tersedia. Coba lagi sesaat lagi.'],503); }
