<?php
declare(strict_types=1);
require dirname(__DIR__).'/lib.php';

header('Content-Type: text/event-stream; charset=utf-8');
header('Cache-Control: no-cache, no-store, no-transform');
header('Connection: keep-alive');
header('X-Accel-Buffering: no');
@ini_set('output_buffering','0');@ini_set('zlib.output_compression','0');ob_implicit_flush(true);
if(function_exists('apache_setenv'))@apache_setenv('no-gzip','1');while(ob_get_level()>0)@ob_end_flush();
echo ': '.str_repeat(' ',2048)."\n\n";flush();

function kce_emit(string $type,array $data=[]):void{echo 'data: '.json_encode(['type'=>$type]+$data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n\n";flush();}
function kce_stream_error(Throwable $e,string $requestId):never{$message=$e->getMessage();$code='AI_UPSTREAM_ERROR';if(stripos($message,'OPENROUTER_API_KEY')!==false)$code='CONFIG_OPENROUTER_KEY';elseif(stripos($message,'database')!==false||stripos($message,'table')!==false||stripos($message,'mysqli')!==false)$code='DATABASE_ERROR';elseif(stripos($message,'HTTP 401')!==false||stripos($message,'HTTP 403')!==false)$code='OPENROUTER_AUTH';elseif(stripos($message,'cURL')!==false)$code='NETWORK_ERROR';error_log("KCE stream [$requestId] ".get_class($e).': '.$message);kce_emit('error',['code'=>$code,'message'=>'Layanan AI gagal merespons. Kode laporan: '.$requestId]);exit;}
function kce_snapshot_results(mysqli $db,int $messageId,array $articles,array $sponsors,string $requestId):void{
    if($articles){$save=$db->prepare('INSERT INTO kce_message_articles(message_id,article_id,title,excerpt,article_url,relevance_score,result_rank) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE title=VALUES(title),excerpt=VALUES(excerpt),article_url=VALUES(article_url),relevance_score=VALUES(relevance_score),result_rank=VALUES(result_rank)');foreach($articles as $rank=>$a){$articleId=(int)$a['id'];$title=(string)$a['title'];$excerpt=(string)$a['excerpt'];$url=(string)$a['url'];$score=(float)$a['score'];$position=$rank+1;$save->bind_param('iisssdi',$messageId,$articleId,$title,$excerpt,$url,$score,$position);$save->execute();}$save->close();}
    if($sponsors){try{$save=$db->prepare('INSERT INTO kce_message_sponsors(message_id,sponsored_content_id,title,body,banner_url,relevance_score,result_rank) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE title=VALUES(title),body=VALUES(body),banner_url=VALUES(banner_url),relevance_score=VALUES(relevance_score),result_rank=VALUES(result_rank)');foreach($sponsors as $rank=>$ad){$sponsorId=(int)$ad['id'];$title=(string)$ad['title'];$body=(string)$ad['body'];$banner=$ad['banner_url']!==null?(string)$ad['banner_url']:null;$score=(float)$ad['score'];$position=$rank+1;$save->bind_param('iisssdi',$messageId,$sponsorId,$title,$body,$banner,$score,$position);$save->execute();}$save->close();}catch(Throwable $e){error_log("KCE sponsor snapshot [$requestId]: ".$e->getMessage());}}
}

if($_SERVER['REQUEST_METHOD']!=='POST'){kce_emit('error',['code'=>'METHOD','message'=>'Method tidak diizinkan']);exit;}
$requestId=bin2hex(random_bytes(6));$in=json_decode((string)file_get_contents('php://input'),true)?:[];$question=trim((string)($in['message']??''));
if($question===''||mb_strlen($question)>4000){kce_emit('error',['code'=>'VALIDATION','message'=>'Pertanyaan wajib diisi (maksimum 4.000 karakter).']);exit;}
if(!kce_verify_human((string)($in['captcha_token']??''))){kce_emit('error',['code'=>'HUMAN_VERIFICATION','message'=>'Verifikasi manusia gagal. Muat ulang halaman dan coba lagi.']);exit;}

try{
    $db=kce_db();$ipHash=kce_ip_hash();$rate=$db->prepare("SELECT COUNT(*) FROM kce_messages m JOIN kce_conversations c ON c.id=m.conversation_id WHERE c.ip_hash=? AND m.role='user' AND m.created_at>=DATE_SUB(NOW(),INTERVAL 1 MINUTE)");$rate->bind_param('s',$ipHash);$rate->execute();$recent=(int)$rate->get_result()->fetch_column();$rate->close();if($recent>=10){kce_emit('error',['code'=>'RATE_LIMIT','message'=>'Terlalu banyak pertanyaan. Tunggu satu menit lalu coba lagi.']);exit;}
    $publicId=trim((string)($_COOKIE['kce_conversation']??''));$conversationId=null;if(preg_match('/^[0-9a-f-]{36}$/i',$publicId)){$s=$db->prepare('SELECT id FROM kce_conversations WHERE public_id=?');$s->bind_param('s',$publicId);$s->execute();$conversationId=$s->get_result()->fetch_column();$s->close();}
    if(!$conversationId){$publicId=kce_uuid();$uid=null;$s=$db->prepare('INSERT INTO kce_conversations(public_id,user_id,ip_hash) VALUES(?,?,?)');$s->bind_param('sis',$publicId,$uid,$ipHash);$s->execute();$conversationId=$s->insert_id;$s->close();kce_set_conversation_cookie($publicId);}
    $s=$db->prepare("INSERT INTO kce_messages(conversation_id,role,content) VALUES(?,'user',?)");$s->bind_param('is',$conversationId,$question);$s->execute();$s->close();$s=$db->prepare('SELECT role,content FROM kce_messages WHERE conversation_id=? ORDER BY id DESC LIMIT 20');$s->bind_param('i',$conversationId);$s->execute();$history=array_reverse($s->get_result()->fetch_all(MYSQLI_ASSOC));$s->close();

    $env=kce_env();$key=trim((string)($env['OPENROUTER_API_KEY']??''));if($key==='')throw new RuntimeException('OPENROUTER_API_KEY belum dikonfigurasi.');
    $models=[trim((string)($env['OPENROUTER_MODEL']??'nvidia/nemotron-nano-12b-v2-vl:free')),trim((string)($env['OPENROUTER_SECONDARY_MODEL']??'openai/gpt-oss-20b:free'))];
    $systemPrompt='Anda adalah Knowledge Commerce Engine KumpulBlogger. Gunakan konteks percakapan sebelumnya untuk memahami pertanyaan lanjutan dan kata rujukan. Jika istilah atau objek pertanyaan memiliki beberapa kemungkinan—misalnya Mataram Kuno dan Mataram Islam—jelaskan perbedaannya atau nyatakan asumsi sebelum menjawab agar fakta tidak tercampur. '
        .'ATURAN AKURASI WAJIB: Jangan mengarang, menebak, atau melengkapi fakta yang tidak diketahui. Jangan membuat nama, angka, tanggal, lokasi, jabatan, statistik, peristiwa, kutipan, URL, referensi, atau nama sumber yang tidak dapat dipastikan. Jangan menganggap premis dalam pertanyaan pengguna sebagai fakta apabila premis tersebut belum pasti; luruskan premis yang keliru atau nyatakan bahwa premis itu perlu diverifikasi. Bedakan secara jelas antara fakta, asumsi, perkiraan, dan opini. Jika informasi tidak diketahui, tidak cukup, ambigu, saling bertentangan, berpotensi sudah berubah, atau Anda tidak yakin, katakan secara eksplisit bahwa informasi yang tersedia tidak cukup untuk memastikannya dan sarankan verifikasi bila perlu. Jangan menyatakan kepastian hanya agar jawaban terlihat lengkap; lebih baik mengakui keterbatasan daripada memberikan informasi yang berpotensi salah. Sebelum memberikan jawaban akhir, periksa setiap klaim faktual dan hapus atau tandai klaim yang tidak dapat dipastikan. '
        .'Jawab akurat, substantif, dan dalam bahasa pengguna. Sesuaikan panjang dengan permintaan: pertanyaan faktual sederhana boleh dijawab singkat, tetapi permintaan seperti "ceritakan", "jelaskan", "bahas", atau permintaan topik luas harus dijawab terstruktur dalam sekitar 5–8 paragraf dengan konteks, kronologi atau pokok pembahasan, fakta penting, dan kesimpulan. Gunakan subjudul atau daftar bila membantu. Hindari pengulangan kalimat, paragraf, fakta, atau kesimpulan; setiap informasi cukup disampaikan satu kali. Jangan menyisipkan iklan; sponsored content ditampilkan aplikasi secara terpisah.';
    $messages=[['role'=>'system','content'=>$systemPrompt]];foreach($history as $h)$messages[]=['role'=>$h['role'],'content'=>$h['content']];
    kce_emit('meta',['conversation_id'=>$publicId,'request_id'=>$requestId,'answer_count'=>count($models)]);

    $successful=[];$articles=[];$sponsors=[];$relatedReady=false;
    foreach($models as $index=>$model){
        $state=['answer'=>'','buffer'=>'','provider_body'=>'','repetition_stopped'=>false];kce_emit('answer_start',['answer_index'=>$index]);
        $ch=curl_init('https://openrouter.ai/api/v1/chat/completions');$payload=['model'=>$model,'messages'=>$messages,'temperature'=>0.2,'max_tokens'=>1300,'reasoning'=>['effort'=>'low','exclude'=>true],'stream'=>true];
        curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>false,CURLOPT_TIMEOUT=>150,CURLOPT_CONNECTTIMEOUT=>15,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$key,'Content-Type: application/json','Accept: text/event-stream','HTTP-Referer: '.($env['KCE_APP_URL']??'https://kumpulblogger.com/kce'),'X-Title: KumpulBlogger KCE'],CURLOPT_POSTFIELDS=>json_encode($payload),CURLOPT_WRITEFUNCTION=>function($ch,string $chunk)use(&$state,$index){$state['buffer'].=$chunk;while(($pos=strpos($state['buffer'],"\n"))!==false){$line=trim(substr($state['buffer'],0,$pos));$state['buffer']=substr($state['buffer'],$pos+1);if($line===''||!str_starts_with($line,'data:'))continue;$data=trim(substr($line,5));if($data==='[DONE]')continue;$json=json_decode($data,true);if(!is_array($json)){$state['provider_body'].=$data;continue;}$delta=$json['choices'][0]['delta']['content']??'';if(is_string($delta)&&$delta!==''){$candidate=$state['answer'].$delta;$candidateLength=mb_strlen($candidate);if($candidateLength>500){$windowLength=180;$tail=mb_substr($candidate,-$windowLength);$earlier=mb_substr($candidate,0,$candidateLength-$windowLength);if(mb_strpos($earlier,$tail)!==false){$state['repetition_stopped']=true;return 0;}}$state['answer']=$candidate;kce_emit('delta',['answer_index'=>$index,'content'=>$delta]);}if(isset($json['error']))$state['provider_body'].=json_encode($json['error']);}return connection_aborted()?0:strlen($chunk);}]);
        $ok=curl_exec($ch);$http=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$curlError=curl_error($ch);curl_close($ch);$answer=trim($state['answer']);
        if((!$ok&&!$state['repetition_stopped'])||$http<200||$http>=300||$answer===''){error_log("KCE stream model [$requestId][$index] HTTP $http cURL $curlError ".mb_substr($state['provider_body'],0,500));kce_emit('model_error',['answer_index'=>$index,'message'=>'Sumber jawaban ini sedang tidak tersedia.']);continue;}
        if($state['repetition_stopped'])error_log("KCE repetition guard [$requestId][$index]: stream dihentikan setelah mendeteksi pengulangan.");
        $s=$db->prepare("INSERT INTO kce_messages(conversation_id,role,content) VALUES(?,'assistant',?)");$s->bind_param('is',$conversationId,$answer);$s->execute();$successful[$index]=['message_id'=>(int)$s->insert_id,'answer'=>$answer];$s->close();kce_emit('answer_done',['answer_index'=>$index]);
        if(!$relatedReady){try{$vector=kce_embedding($question,'query');foreach(kce_relevant_articles($db,$vector)as$a)$articles[]=['id'=>(int)$a['id'],'title'=>$a['title'],'excerpt'=>$a['excerpt'],'url'=>$a['url'],'score'=>round((float)$a['score'],4)];foreach(kce_active_sponsors($db,$vector)as$ad)$sponsors[]=['id'=>(int)$ad['id'],'title'=>$ad['title'],'body'=>$ad['body'],'banner_url'=>kce_public_url($ad['banner_url']),'score'=>round((float)$ad['score'],4),'impression_token'=>kce_sign((int)$ad['id'],$publicId)];}catch(Throwable $e){error_log("KCE embedding/history [$requestId]: ".$e->getMessage());}$relatedReady=true;}
        kce_snapshot_results($db,$successful[$index]['message_id'],$articles,$sponsors,$requestId);kce_emit('related',['answer_index'=>$index,'articles'=>$articles,'sponsored'=>$sponsors]);
    }
    if(!$successful)throw new RuntimeException('Kedua model OpenRouter gagal memberikan jawaban.');

    kce_emit('done',['request_id'=>$requestId,'completed_models'=>array_keys($successful)]);
}catch(Throwable $e){kce_stream_error($e,$requestId);}
