<?php
declare(strict_types=1);
session_start();
if(!isset($_SESSION['loggedin'])){header('Location: ../admin/login.php');exit;}
require __DIR__.'/lib.php';

$messages=[];$positions=[];$assistantIds=[];$loadError='';
try{
        $db=kce_db();
        $result=$db->query("SELECT m.id,m.role,m.content,m.created_at,c.public_id conversation_public_id,(SELECT MAX(u.id) FROM kce_messages u WHERE u.conversation_id=m.conversation_id AND u.role='user' AND u.id<=m.id) turn_id FROM kce_messages m JOIN kce_conversations c ON c.id=m.conversation_id WHERE m.created_at>=DATE_SUB(NOW(),INTERVAL 12 HOUR) ORDER BY turn_id DESC,m.id ASC");
        $rows=$result->fetch_all(MYSQLI_ASSOC);
        foreach($rows as $row){$id=(int)$row['id'];$positions[$id]=count($messages);$messages[]=['id'=>$id,'role'=>$row['role'],'content'=>$row['content'],'created_at'=>$row['created_at'],'conversation_public_id'=>$row['conversation_public_id'],'articles'=>[],'sponsored'=>[]];if($row['role']==='assistant')$assistantIds[]=$id;}
        if($assistantIds){
            $ids=implode(',',array_map('intval',$assistantIds));
            $result=$db->query("SELECT message_id,article_id,title,excerpt,article_url FROM kce_message_articles WHERE message_id IN ($ids) ORDER BY message_id,result_rank");
            while($row=$result->fetch_assoc()){$messageId=(int)$row['message_id'];if(isset($positions[$messageId]))$messages[$positions[$messageId]]['articles'][]=['title'=>$row['title'],'excerpt'=>$row['excerpt'],'url'=>$row['article_url']];}
            $result=$db->query("SELECT message_id,sponsored_content_id,title,body,banner_url FROM kce_message_sponsors WHERE message_id IN ($ids) ORDER BY message_id,result_rank");
            while($row=$result->fetch_assoc()){$messageId=(int)$row['message_id'];if(!isset($positions[$messageId]))continue;$sponsorId=(int)$row['sponsored_content_id'];$messages[$positions[$messageId]]['sponsored'][]=['id'=>$sponsorId,'title'=>$row['title'],'body'=>$row['body'],'banner_url'=>kce_public_url($row['banner_url'])];}
        }
}catch(Throwable $e){error_log('KCE history page: '.$e->getMessage());$loadError='History chat tidak dapat dimuat saat ini.';}
function history_json(mixed $value):string{return htmlspecialchars((string)json_encode($value,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT),ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>History Chat KCE</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/kce.css?v=20260729-2"><style>.history-shell{width:min(980px,calc(100% - 32px));margin:auto;padding:26px 0 50px}.history-head{margin-bottom:22px;padding:24px 26px;border-radius:22px;background:linear-gradient(120deg,#113c30,#0b6b4d);color:#fff}.history-head h1{margin:.3rem 0;font:800 clamp(25px,4vw,38px)/1.2 Manrope}.history-head p{margin:0;color:#c8ddd5}.history-list{padding:28px;border:1px solid #e0e3da;border-radius:24px;background:#fffc;box-shadow:0 18px 55px #263c2e12}.history-item{display:flex;flex-direction:column}.history-time{margin:-10px 4px 12px;color:#84908a;font-size:11px}.history-empty{padding:60px 20px;text-align:center;color:#68756f}.history-list .bubble{white-space:normal}.history-list .bubble.user{white-space:pre-wrap}.history-list .bubble.ai{max-width:88%}.ai-content p{margin:.45rem 0}.ai-content a{color:#0b6b4d;font-weight:700}.article-results{margin:0 0 24px}.article-heading{margin-bottom:10px;color:#0b6b4d;font:700 11px Manrope;letter-spacing:1.5px}.article-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.article-grid article{padding:14px;border:1px solid #dce6df;border-radius:14px;background:#fff}.article-grid h3{margin:5px 0;font:700 14px Manrope}.article-grid p{color:#68756f;font-size:12px}.article-grid a{color:#0b6b4d;font-size:12px;font-weight:700}.notice{padding:14px;border-radius:12px;background:#fff3cd;color:#6d5711}@media(max-width:700px){.history-list{padding:18px 14px}.article-grid{grid-template-columns:1fr}.history-list .bubble.ai{max-width:96%}}</style></head><body><div class="ambient one"></div><div class="ambient two"></div><main class="history-shell"><header class="history-head"><span>KNOWLEDGE COMMERCE ENGINE</span><h1>Seluruh chat 12 jam terakhir</h1><p>Monitor admin untuk seluruh pertanyaan dan jawaban pengguna, diurutkan dari yang paling baru.</p></header><section class="history-list">
<?php if($loadError!==''):?><div class="notice"><?=htmlspecialchars($loadError)?></div><?php elseif(!$messages):?><div class="history-empty"><strong>Belum ada percakapan dalam 12 jam terakhir.</strong></div><?php else:foreach($messages as $message):?><article class="history-item"><div class="bubble <?=$message['role']==='assistant'?'ai':'user'?>"><?php if($message['role']==='assistant'):?><span class="ai-label">JAWABAN AI</span><div class="ai-content" data-markdown="<?=history_json($message['content'])?>"></div><?php else:?><?=htmlspecialchars($message['content'])?><?php endif;?></div><time class="history-time"><?=htmlspecialchars(date('d/m/Y H:i',strtotime($message['created_at'])))?> &middot; Percakapan <?=htmlspecialchars(substr($message['conversation_public_id'],0,8))?></time><?php if($message['articles']):?><section class="article-results"><div class="article-heading">ARTIKEL RELEVAN DARI KUMPULBLOGGER</div><div class="article-grid"><?php foreach($message['articles'] as $article):?><article><h3><?=htmlspecialchars($article['title'])?></h3><p><?=htmlspecialchars($article['excerpt'])?></p><a href="<?=htmlspecialchars($article['url'])?>" target="_blank" rel="noopener">Baca artikel &rarr;</a></article><?php endforeach;?></div></section><?php endif;?><?php if($message['sponsored']):?><section class="sponsored-wrap"><div class="sponsored-heading">SPONSORED CONTENT &middot; IKLAN</div><?php foreach($message['sponsored'] as $ad):$conversationPublicId=(string)$message['conversation_public_id'];$clickUrl='api/event.php?'.http_build_query(['id'=>$ad['id'],'type'=>'click','conversation_id'=>$conversationPublicId,'token'=>kce_sign((int)$ad['id'],$conversationPublicId)]);?><article class="sponsor"><div><h3><?=htmlspecialchars($ad['title'])?></h3><p><?=htmlspecialchars($ad['body'])?></p><a href="<?=htmlspecialchars($clickUrl)?>" target="_blank" rel="noopener sponsored">Kunjungi sponsor &rarr;</a></div><?php if($ad['banner_url']):?><img src="<?=htmlspecialchars($ad['banner_url'])?>" alt="Mini banner <?=htmlspecialchars($ad['title'])?>" loading="lazy"><?php endif;?></article><?php endforeach;?></section><?php endif;?></article><?php endforeach;endif;?></section></main><script>
(()=>{const esc=s=>{const d=document.createElement('div');d.textContent=String(s??'');return d.innerHTML};const inline=source=>{const links=[];let s=source;const save=(label,url)=>{const key=`@@L${links.length}@@`;links.push(`<a href="${url}" target="_blank" rel="noopener noreferrer nofollow">${label}</a>`);return key};s=s.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/gi,(_,label,url)=>save(label,url));s=s.replace(/(^|[\s(])(https?:\/\/[^\s<]+)/gi,(all,prefix,url)=>{let trailing='';while(/[.,;:!?)]$/.test(url)){trailing=url.slice(-1)+trailing;url=url.slice(0,-1)}return prefix+save(url,url)+trailing});s=s.replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>');links.forEach((v,i)=>s=s.replace(`@@L${i}@@`,v));return s};function markdown(value){const lines=esc(value).replace(/\r/g,'').split('\n');let html='',p=[],list=null;const fp=()=>{if(p.length){html+='<p>'+inline(p.join(' '))+'</p>';p=[]}};const fl=()=>{if(list){html+=`</${list}>`;list=null}};for(const raw of lines){const line=raw.trim();let m;if(!line){fp();fl();continue}if((m=line.match(/^(#{1,4})\s+(.+)$/))){fp();fl();const n=Math.min(4,m[1].length+1);html+=`<h${n}>${inline(m[2])}</h${n}>`}else if((m=line.match(/^[-*]\s+(.+)$/))){fp();if(list!=='ul'){fl();html+='<ul>';list='ul'}html+='<li>'+inline(m[1])+'</li>'}else if((m=line.match(/^\d+[.)]\s+(.+)$/))){fp();if(list!=='ol'){fl();html+='<ol>';list='ol'}html+='<li>'+inline(m[1])+'</li>'}else p.push(line)}fp();fl();return html}document.querySelectorAll('[data-markdown]').forEach(el=>{try{el.innerHTML=markdown(JSON.parse(el.dataset.markdown))}catch(e){el.textContent=el.dataset.markdown}})})();
</script></body></html>
