<?php
$kceEnvFile=dirname(__DIR__,2).'/.env';
$kceFileEnv=is_readable($kceEnvFile)?(parse_ini_file($kceEnvFile,false,INI_SCANNER_RAW)?:[]):[];
$kceProcessEnv=getenv();
$kceEnv=array_merge($kceFileEnv,is_array($kceProcessEnv)?$kceProcessEnv:[]);
$kceSiteKey=(string)($kceEnv['RECAPTCHA_SITE_KEY']??'');
$kceInitialQuestion=mb_substr(trim((string)($_GET['q']??'')),0,4000);
$paidAiMessage='Halo {NAMA PEMILIK PLATFORM}, saya ingin request paket AI berbayar KCE Rp150.000/bulan.';
$paymentInfo=str_replace('{{ISIPESAN}}',rawurlencode($paidAiMessage),(string)($kceEnv['PAYMENT_INFO']??''));
$paidAiWhatsappUrl='';
if(preg_match("~https://wa\\.me/[^\\s'\"<>]+~i",$paymentInfo,$whatsappMatch))$paidAiWhatsappUrl=$whatsappMatch[0];
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Knowledge Commerce Engine KumpulBlogger"><title>KCE — Tanya, temukan, tumbuh</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/kce.css?v=20260729-4">
<link rel="stylesheet" href="assets/narrative.css?v=20260730-2"><script src="https://www.google.com/recaptcha/api.js?render=<?=htmlspecialchars($kceSiteKey,ENT_QUOTES,'UTF-8')?>"></script></head><body><div class="ambient one"></div><div class="ambient two"></div><main class="shell">
 <header><a class="brand" href="./"><span class="brandmark">K</span><span>Kumpul<span>Knowledge</span></span></a></header>
 <section class="chat-card"><div class="intro" id="intro"><span class="eyebrow">KNOWLEDGE COMMERCE ENGINE</span><h1>Pengetahuan yang membuka<br><em>kemungkinan baru.</em></h1><p>Tanyakan apa saja. Dapatkan dua jawaban streaming dari model AI berbeda, dilengkapi artikel relevan dan rekomendasi sponsor yang selalu ditandai secara transparan.</p><div class="prompts"><button>Apa strategi konten untuk bisnis kecil?</button><button>Jelaskan pemasaran berbasis komunitas</button><button>Bagaimana memulai blog profesional?</button></div></div>
 <div class="messages" id="messages" aria-live="polite"></div>
<aside class="privacy-note"><b>Privasi & transparansi data</b><span>Dengan menggunakan chat, Anda menyetujui cookie untuk memulihkan history. Percakapan dicatat untuk menyediakan layanan dan mengukur relevansi. Advertiser yang relevan menerima bukti performa agregat—seperti impression, click, CTR, dan biaya—bukan isi lengkap chat atau identitas Anda.</span></aside> <form id="chatForm" class="composer" data-initial-question="<?=htmlspecialchars($kceInitialQuestion,ENT_QUOTES,'UTF-8')?>"><div class="ai-disclaimer" role="note"><strong>Perhatian:</strong> model AI gratis ini dapat memberikan informasi yang keliru atau berhalusinasi. Selalu verifikasi informasi penting. Tersedia versi berbayar <b>Rp150.000/bulan</b> menggunakan pilihan model AI GPT 5.5, Claude Opus 5, Kimi K3, atau GLM 5.2.<?php if($paidAiWhatsappUrl!==''):?> <a href="<?=htmlspecialchars($paidAiWhatsappUrl,ENT_QUOTES,'UTF-8')?>" target="_blank" rel="noopener noreferrer">Hubungi Kukuh TW via WhatsApp untuk request AI berbayar →</a><?php endif;?></div><textarea id="question" rows="1" maxlength="4000" placeholder="Tulis pertanyaan Anda..." aria-label="Pertanyaan" required></textarea><button type="submit" id="send" aria-label="Kirim"><svg viewBox="0 0 24 24"><path d="m5 12 14-7-4 14-3-6-7-1Z"/></svg></button><small>Enter untuk kirim · Shift + Enter untuk baris baru</small></form>
 </section>
 <section class="about"><div class="section-kicker">TENTANG KCE</div><div class="about-grid"><h2>Ketika pengetahuan bertemu<br><em>peluang yang relevan.</em></h2><div><p><strong>Knowledge Commerce Engine (KCE)</strong> adalah mesin pengetahuan berbasis AI dari KumpulBlogger yang menghubungkan pertanyaan pengguna dengan jawaban yang berguna dan informasi komersial yang sesuai konteks.</p><p>KCE memahami makna pertanyaan melalui pencocokan semantik—bukan sekadar kata yang sama—agar sponsored content tetap berhubungan dengan kebutuhan pengguna.</p></div></div></section>
 <section class="how"><div class="section-head"><div><span class="section-kicker">CARA KERJA</span><h2>Sederhana bagi pengguna.<br>Cerdas di balik layar.</h2></div><p>Satu pertanyaan melewati dua jalur independen. Hasilnya disajikan dengan label yang jelas.</p></div><div class="steps"><article><span>01</span><i>?</i><h3>Anda bertanya</h3><p>Tulis pertanyaan, kebutuhan, atau topik yang ingin dipahami.</p></article><article><span>02</span><i>✦</i><h3>AI menjawab</h3><p>AI menyusun jawaban berdasarkan konteks percakapan.</p></article><article><span>03</span><i>⌁</i><h3>Relevansi dicocokkan</h3><p>Embedding 2048 dimensi mencari sponsor aktif yang paling relevan.</p></article><article><span>04</span><i>✓</i><h3>Ditampilkan terpisah</h3><p>Jawaban AI dan konten berbayar tidak disamarkan atau dicampurkan.</p></article></div></section>
 <section class="transparency"><div><span class="section-kicker light">TRANSPARANSI SEJAK AWAL</span><h2>Dua jalur.<br>Satu pengalaman yang jujur.</h2><p>Sponsored content tidak dimasukkan ke prompt dan tidak memengaruhi jawaban AI. Sponsor dicocokkan setelah jawaban dibuat, lalu tampil dalam komponen berlabel jelas.</p><ul><li>✓ Jawaban AI memiliki identitas visual tersendiri</li><li>✓ Setiap iklan bertanda “Sponsored Content · Iklan”</li><li>✓ Relevansi berdasarkan konteks, bukan penyamaran promosi</li></ul></div><div class="separation-demo"><div class="demo-ai"><small>JAWABAN AI</small><b></b><b></b><b></b></div><em>JAWABAN DAN IKLAN TERPISAH</em><div class="demo-ad"><small>SPONSORED CONTENT · IKLAN</small><b></b><b></b></div></div></section>
 <section class="audiences"><article><span>UNTUK PENGGUNA</span><h2>Temukan pemahaman,<br>bukan sekadar tautan.</h2><p>Dapatkan jawaban terstruktur dan temukan solusi terkait tanpa kehilangan kendali atas mana informasi AI dan mana promosi.</p><a href="#chatForm">Mulai bertanya →</a></article><article class="advertiser"><span>UNTUK ADVERTISER</span><h2>Hadir pada momen<br>yang relevan.</h2><p>Jangkau pengguna berdasarkan maksud pertanyaannya. Atur campaign dan pantau impression, click, CTR, serta biaya.</p><a class="cta" href="../login.php">Masuk & pasang iklan KCE →</a></article></section>
 <section class="closing"><span class="section-kicker">MULAI SEKARANG</span><h2>Satu pertanyaan dapat membuka<br><em>kemungkinan baru.</em></h2><a class="cta dark" href="#chatForm">Tanyakan sesuatu ↑</a></section>
 <footer><span>Jawaban dibuat oleh AI dan dapat keliru. Verifikasi informasi penting.</span><span>Sponsored content selalu diberi label.</span></footer>
</main><script src="assets/kce.js?v=20260730-1"></script></body></html>
